# Generated by Django 6.1 on 2026-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_key', models.CharField(max_length=64)),
                ('ts', models.DateTimeField(db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ts'],
                'indexes': [models.Index(fields=['thing_key', 'ts'], name='dashboard_h_thing_k_bb5357_idx')],
                'constraints': [models.UniqueConstraint(fields=('thing_key', 'ts'), name='uniq_sample_ts')],
            },
        ),
    ]
