# Generated by Django 6.1 on 2026-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZCSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://third.zcsazzurroportal.com:19003/', max_length=255)),
                ('thing_key_enc', models.TextField(blank=True, default='')),
                ('client_code_enc', models.TextField(blank=True, default='')),
                ('auth_code_enc', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ZCS configuration',
                'verbose_name_plural': 'ZCS configuration',
            },
        ),
    ]
